# Generated by Django 3.1.5 on 2021-01-22 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('valid_start_date', models.DateTimeField(help_text='license start date', null=True)),
                ('valid_end_date', models.DateTimeField(help_text='license end date', null=True)),
                ('stock', models.IntegerField(null=True)),
                ('campaign', models.CharField(max_length=32)),
                ('enable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeem_time', models.DateTimeField(auto_now=True)),
                ('used', models.BooleanField(default=False)),
                ('customer_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.customer')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.promocode')),
            ],
        ),
    ]
