# Generated by Django 3.1.5 on 2021-01-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customerpromocode_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpromocode',
            name='id',
        ),
        migrations.AlterField(
            model_name='customerpromocode',
            name='customer_code',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
