# Generated by Django 3.1.5 on 2021-01-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210125_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpromocode',
            name='transfer',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
