# Generated by Django 3.1.5 on 2021-01-26 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210126_0247'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerpromocode',
            unique_together={('customer_code', 'promo_code', 'transfer')},
        ),
    ]
