# Generated by Django 3.1.5 on 2021-01-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210126_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpromocode',
            name='transfer',
            field=models.UUIDField(null=True),
        ),
    ]
