# Generated by Django 3.1.5 on 2021-01-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210126_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpromocode',
            name='transfer',
            field=models.UUIDField(default='00000000-0000-0000-0000-000000000000'),
        ),
    ]
