# Generated by Django 3.1.5 on 2021-01-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210126_0328'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customerpromocode',
            name='customer promo constraint',
        ),
        migrations.AlterUniqueTogether(
            name='customerpromocode',
            unique_together={('customer_code', 'promo_code', 'transfer')},
        ),
    ]
