# Generated by Django 3.1.5 on 2021-01-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_promocode_meta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
    ]
